# Generated by Django 5.0.3 on 2025-10-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_processed_notification_queue_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki'), ('urgent', 'Pilny')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_reminder', 'Przypomnienie o wizycie'), ('repair_status', 'Status naprawy'), ('invoice', 'Faktura'), ('promotional', 'Promocyjna'), ('system', 'Systemowa'), ('service_reminder', 'Przypomnienie o serwisie'), ('chat_message', 'Nowa wiadomość'), ('ai_diagnosis_ready', 'Diagnoza AI gotowa'), ('parts_low_stock', 'Niski stan magazynowy'), ('supplier_delivery', 'Dostawa od dostawcy'), ('payment_reminder', 'Przypomnienie o płatności'), ('service_feedback_request', 'Prośba o opinię')], max_length=50),
        ),
    ]
