# Generated by Django 5.0.3 on 2025-10-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicleservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='workshop',
        ),
    ]
