# Generated by Django 5.0.3 on 2025-11-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_remove_vehicle_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostics',
            name='email_notification',
            field=models.BooleanField(default=False, help_text='Send email notification to client'),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='next_inspection_date',
            field=models.DateField(blank=True, help_text='Date for next periodic inspection', null=True),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='sms_notification',
            field=models.BooleanField(default=False, help_text='Send SMS notification to client'),
        ),
    ]
