# Generated by Django 5.0.3 on 2025-11-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_assigned_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('service', 'Serwis'), ('inspection', 'Przegląd'), ('diagnostic', 'Diagnostyka'), ('repair', 'Naprawa'), ('maintenance', 'Konserwacja'), ('other', 'Inne')], default='service', help_text='Typ wizyty (serwis, przegląd, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_estimate',
            field=models.IntegerField(blank=True, help_text='Szacowany czas trwania w minutach', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_description',
            field=models.TextField(blank=True, help_text='Szczegółowy opis problemu lub wymaganej usługi', null=True),
        ),
    ]
