# Generated by Django 5.0.3 on 2025-11-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Zaplanowane'), ('in_progress', 'W trakcie'), ('completed', 'Skończone')], default='scheduled', max_length=20),
        ),
    ]
