# Generated by Django 5.0.3 on 2025-12-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_migrate_appointment_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('service', 'Service'), ('inspection', 'Inspection'), ('diagnostic', 'Diagnostic'), ('repair', 'Repair'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='service', help_text='Typ wizyty (serwis, przegląd, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
    ]
