# Generated by Django 5.0.3 on 2025-10-25 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_change_supplier_to_foreignkey'),
        ('workshops', '0003_add_geolocation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Niski stan'), ('out_of_stock', 'Brak na stanie'), ('reorder_point', 'Punkt uzupełnienia')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.part')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='workshops.workshop')),
            ],
            options={
                'unique_together': {('part', 'workshop', 'alert_type')},
            },
        ),
    ]
