import { createUseStyles } from "react-jss";
import {
	COLOR_SURFACE,
	COLOR_TEXT_PRIMARY,
	COLOR_TEXT_SECONDARY,
} from "../../constants";

const useStyles = createUseStyles({
	container: {
		padding: "24px",
		maxWidth: "1200px",
		margin: "0 auto",
	},
	header: {
		display: "flex",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: "32px",
		flexWrap: "wrap",
		gap: "16px",
	},
	title: {
		fontSize: "32px",
		fontWeight: "600",
		color: "#1f2937",
		margin: 0,
	},
	actions: {
		display: "flex",
		gap: "12px",
		flexWrap: "wrap",
	},
	primaryButton: {
		backgroundColor: "#3b82f6",
		color: "white",
		border: "none",
		borderRadius: "8px",
		padding: "12px 24px",
		fontSize: "14px",
		fontWeight: "500",
		cursor: "pointer",
		transition: "all 0.2s ease",
		"&:hover": {
			backgroundColor: "#2563eb",
			transform: "translateY(-1px)",
		},
		"&:disabled": {
			backgroundColor: "#9ca3af",
			cursor: "not-allowed",
			transform: "none",
		},
	},
	secondaryButton: {
		backgroundColor: "#f3f4f6",
		color: "#374151",
		border: "1px solid #d1d5db",
		borderRadius: "8px",
		padding: "12px 24px",
		fontSize: "14px",
		fontWeight: "500",
		cursor: "pointer",
		transition: "all 0.2s ease",
		"&:hover": {
			backgroundColor: "#e5e7eb",
			transform: "translateY(-1px)",
		},
	},
	dangerButton: {
		backgroundColor: "#ef4444",
		color: "white",
		border: "none",
		borderRadius: "8px",
		padding: "12px 24px",
		fontSize: "14px",
		fontWeight: "500",
		cursor: "pointer",
		transition: "all 0.2s ease",
		"&:hover": {
			backgroundColor: "#dc2626",
			transform: "translateY(-1px)",
		},
		"&:disabled": {
			backgroundColor: "#9ca3af",
			cursor: "not-allowed",
			transform: "none",
		},
	},
	errorMessage: {
		backgroundColor: "#fef2f2",
		border: "1px solid #fecaca",
		color: "#dc2626",
		padding: "12px 16px",
		borderRadius: "8px",
		marginBottom: "24px",
		fontSize: "14px",
	},
	loadingContainer: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		padding: "64px 24px",
		color: "#6b7280",
	},
	loadingSpinner: {
		width: "40px",
		height: "40px",
		border: "4px solid #f3f4f6",
		borderTop: "4px solid #3b82f6",
		borderRadius: "50%",
		animation: "$spin 1s linear infinite",
		marginBottom: "16px",
	},
	"@keyframes spin": {
		"0%": { transform: "rotate(0deg)" },
		"100%": { transform: "rotate(360deg)" },
	},
	profileCard: {
		backgroundColor: COLOR_SURFACE,
		borderRadius: "12px",
		border: "1px solid #e5e7eb",
		overflow: "hidden",
		boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
	},
	profileHeader: {
		display: "flex",
		justifyContent: "space-between",
		alignItems: "center",
		padding: "24px",
		borderBottom: "1px solid #e5e7eb",
		backgroundColor: "#f9fafb",
	},
	profileInfo: {
		"& h2": {
			fontSize: "20px",
			fontWeight: "600",
			color: "#1f2937",
			margin: "0 0 4px 0",
		},
	},
	subtitle: {
		fontSize: "14px",
		color: "#6b7280",
		margin: 0,
	},
	photoContainer: {
		display: "flex",
		alignItems: "center",
	},
	profilePhoto: {
		width: "80px",
		height: "80px",
		borderRadius: "50%",
		objectFit: "cover",
		border: "3px solid #e5e7eb",
	},
	profileDetails: {
		padding: "24px",
	},
	detailRow: {
		display: "flex",
		alignItems: "center",
		padding: "12px 0",
		borderBottom: "1px solid #f3f4f6",
		"&:last-child": {
			borderBottom: "none",
		},
	},
	label: {
		fontSize: "14px",
		fontWeight: "500",
		color: "#374151",
		minWidth: "140px",
	},
	value: {
		fontSize: "14px",
		color: "#6b7280",
		flex: 1,
	},
	emptyState: {
		textAlign: "center",
		padding: "64px 24px",
		backgroundColor: COLOR_SURFACE,
		borderRadius: "12px",
		border: "1px solid #e5e7eb",
		"& h3": {
			fontSize: "20px",
			fontWeight: "600",
			color: "#1f2937",
			margin: "16px 0 8px 0",
		},
		"& p": {
			fontSize: "14px",
			color: "#6b7280",
			marginBottom: "24px",
		},
	},
	emptyIcon: {
		fontSize: "48px",
		opacity: 0.5,
	},
	modalForm: {
		display: "flex",
		flexDirection: "column",
		gap: "20px",
	},
	formGroup: {
		display: "flex",
		flexDirection: "column",
		gap: "8px",
	},
	formLabel: {
		fontSize: "14px",
		fontWeight: "500",
		color: "#374151",
	},
	formInput: {
		padding: "12px",
		border: "1px solid #d1d5db",
		borderRadius: "8px",
		fontSize: "14px",
		transition: "border-color 0.2s ease",
		"&:focus": {
			outline: "none",
			borderColor: "#3b82f6",
			boxShadow: "0 0 0 3px rgba(59, 130, 246, 0.1)",
		},
	},
	formSelect: {
		padding: "12px",
		border: "1px solid #d1d5db",
		borderRadius: "8px",
		fontSize: "14px",
		backgroundColor: COLOR_SURFACE,
		cursor: "pointer",
		"&:focus": {
			outline: "none",
			borderColor: "#3b82f6",
			boxShadow: "0 0 0 3px rgba(59, 130, 246, 0.1)",
		},
	},
	photoPreview: {
		marginTop: "12px",
		display: "flex",
		justifyContent: "center",
	},
	previewImage: {
		width: "120px",
		height: "120px",
		borderRadius: "8px",
		objectFit: "cover",
		border: "1px solid #e5e7eb",
	},
	modalActions: {
		display: "flex",
		justifyContent: "flex-end",
		gap: "12px",
		marginTop: "24px",
		paddingTop: "20px",
		borderTop: "1px solid #e5e7eb",
	},
});

export default useStyles;
