# Generated by Django 5.0.3 on 2025-10-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_remove_workshop_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='address_full',
            field=models.TextField(blank=True, help_text='Pełny adres strukturalny', null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Google Places API ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Szerokość geograficzna', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Długość geograficzna', max_digits=9, null=True),
        ),
    ]
