# Generated by Django 5.0.3 on 2025-11-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_add_geolocation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, help_text='Opcjonalna godzina początku przerwy', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Opcjonalna godzina końca przerwy', null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_recurring', models.BooleanField(default=False, help_text='Czy przerwa jest cykliczna (np. święta)')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='workshops.workshop')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')])),
                ('start_time', models.TimeField(help_text='Godzina otwarcia')),
                ('end_time', models.TimeField(help_text='Godzina zamknięcia')),
                ('is_available', models.BooleanField(default=True, help_text='Czy warsztat jest dostępny tego dnia')),
                ('slot_duration', models.IntegerField(default=60, help_text='Długość pojedynczego slotu w minutach')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='workshops.workshop')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('workshop', 'weekday')},
            },
        ),
    ]
