# Generated by Django 5.0.3 on 2025-11-13 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_workshopbreak_workshopavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, help_text='Opcjonalna godzina początku przerwy', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Opcjonalna godzina końca przerwy', null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_recurring', models.BooleanField(default=False, help_text='Czy przerwa jest cykliczna')),
                ('workshop_mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='workshops.workshopmechanic')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='MechanicAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')])),
                ('start_time', models.TimeField(help_text='Godzina rozpoczęcia pracy')),
                ('end_time', models.TimeField(help_text='Godzina zakończenia pracy')),
                ('is_available', models.BooleanField(default=True, help_text='Czy mechanik jest dostępny tego dnia')),
                ('workshop_mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='workshops.workshopmechanic')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('workshop_mechanic', 'weekday')},
            },
        ),
    ]
