# Generated by Django 5.0.3 on 2025-03-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField()),
                ('name', models.CharField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True)),
                ('phone_number', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(blank=True, max_length=500, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('owner', 'owner'), ('mechanic', 'mechanic'), ('client', 'client')], default='client', max_length=20)),
                ('car_workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.carworkshop')),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set_custom', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions_custom', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
