# Generated by Django 5.0.3 on 2025-12-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_preferred_contact_method_user_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specializations',
            field=models.JSONField(blank=True, default=list, help_text='List of vehicle brands this mechanic specializes in (for mechanics only)'),
        ),
    ]
